apiVersion: v1
kind: Template
metadata:
  name: jenkins-slave-play
labels:
  template: jenkins-slave-play
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      slave-directory: /opt/app-root/jenkins
      slave-label: play
    labels:
      role: jenkins-slave
    name: jenkins-slave-play
  spec:
    tags:
    - name: 'latest'
      importPolicy:
        scheduled: true
      annotations:
        description: 'Provides Jenkins slaves with Play Framework'
        tags: jenkins-slave-play
      from:
        kind: DockerImage
        name: 'outtherelabs/jenkins-slave-play:latest'
