apiVersion: v1
kind: Template
metadata:
  name: s2i-scala
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      slave-directory: /opt/app-root/jenkins
      slave-label: java8
    labels:
      role: jenkins-slave
    name: java8-jenkins-slave
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Modifies the openshift/base-centos7 to run as Jenkins slave
    labels:
      name: java8-slave
      template: jenkins-slave-builder
    name: java8-jenkins-slave
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: java8-jenkins-slave:latest
    resources: {}
    source:
      contextDir: java8
      git:
        ref: master
        uri: https://github.com/OutThereLabs/jenkins-slaves.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: openshift/base-centos7
      type: Docker
    triggers:
    - github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
      type: GitHub
    - generic:
        secret: "${GENERIC_WEBHOOK_SECRET}"
      type: Generic
parameters:
  - name: "GITHUB_WEBHOOK_SECRET"
    displayName: "GitHub Webhook Secret"
    description: "A secret string used to configure the GitHub webhook."
    generate: "expression"
    from: "[a-zA-Z0-9]{40}"
  - name: "GENERIC_WEBHOOK_SECRET"
    displayName: "GitHub Webhook Secret"
    description: "A secret string used to configure the GitHub webhook."
    generate: "expression"
    from: "[a-zA-Z0-9]{40}"
